### ISSUE TITLE
Electric Core Machine data clearing

### ISSUE THREAD

**Issue by Bunnky** [RelativoBR/Supreme#1]
When setting up an Electric Core Machine and supplying it with materials, you cannot reset the machines current material without finishing it. The only way to do this is to place the machine in a different location, as the material in the machine seems to be location based.

I'd like to suggest giving players the ability to clear the data, as its very easy to want to switch gears to another material without having to wait for the previous to finish. Breaking the machine, clicking a gui element, or even a tool would do the trick!

**Comment by RelativoBR** [comment]
we will fix this bug, thanks for the feedback.

I'm currently working to make this addon compatible with the old addon, but we will respond to this request.

**Comment by RelativoBR** [comment]
Fix in Build 7 (Supreme v1.3.0)

https://thebusybiscuit.github.io/builds/RelativoBR/Supreme/main/
