### ISSUE TITLE
Item Converter + Reinforced Spawner Incompatibility

### ISSUE THREAD

**Issue by JasperChaseTOQ** [RelativoBR/Supreme#13]
## Description (Required)
when you place a reinforced spawner into the item converter it does not save the data but it gives the reinforced spawner in the guide breaking it
## Steps to reproduce the Issue (Required)
![2022-09-16_14 49 44](https://user-images.githubusercontent.com/103849596/190711031-f7b7842c-7db4-4bb0-ae8c-6a7557ab867a.png)
![2022-09-16_14 49 47](https://user-images.githubusercontent.com/103849596/190711035-de5667f8-c6d2-4ae4-bd70-7085f0472809.png)
![2022-09-16_14 50 09](https://user-images.githubusercontent.com/103849596/190711038-57852bf3-44af-4177-b672-3210eed81750.png)
![2022-09-16_14 50 14](https://user-images.githubusercontent.com/103849596/190711040-6b56d7dd-7177-4689-b8e7-2f022b4afd99.png)
![2022-09-16_14 50 17](https://user-images.githubusercontent.com/103849596/190711043-f5fc5ae2-bd08-47f4-8e29-1647307065ab.png)

## Expected behavior (Required)

for the item converter to not break reinforced spawners

## Environment (Required)

 - Minecraft Version: 1.19
 - CS-CoreLib Version:
 - Slimefun Version: 1027
 - Plugin Version: 11

**Comment by RelativoBR** [comment]
fix in PR #15
