### ISSUE TITLE
The power units of most machines are inconsistent with the facts

### ISSUE THREAD

**Issue by Violet-Nonbloosom** [RelativoBR/Supreme#16]
## Description (Required)
According to the Slimefun Guide, most machines use "J/s" as their power unit.

However, when I was using SUPREME_TECH_GENERATOR, I occured to realise that 2 kW of power supply was **UNABLE** to make SUPREME_TECH_GENERATOR work properly.

According to the code, the power of SUPREME_TECH_GENERATOR is obviously 2000 **J/slimefun tick**, **RATHER THAN J/s**.

It is the same with most machines (including generators) using "J/s" as their power unit.

## Steps to reproduce the Issue (Required)
1. Place a ENERGY_REGULATOR, 5 SOLAR_GENERATORs and a SUPREME_ELECTRIC_CORE_I in the same energy network.
2. Put a cobblestone into the SUPREME_ELECTRIC_CORE_I, and you can observe that the machine is working **INTERMITTENTLY**.
3. Place 5 more SOLAR_GENERATORs, and you can observe that the machine is working **PROPERLY**.

## Expected behavior (Required)
- Adjust the units and values in the item lores, or...
- Adjust the actual power, so that they are consistent with the marked power.

## Server Log / Error Report
This is needless.

## Environment (Required)
 - Minecraft Version: 1.19.2
 - CS-CoreLib Version: 
 - Slimefun Version: RC - 32
 - Plugin Version: vDev - 13 (git 71414cc6)

**Comment by RelativoBR** [comment]
Thanks for reporting the incident, I will make the correction.

**Comment by RelativoBR** [comment]
problem related to [issues/17](https://github.com/RelativoBR/Supreme/issues/19), corrected the value of energy required for the machine to work. Fixed On branch october-2022
