### ISSUE TITLE
High tier Mutation TechMobs perform as well as those at tier 1, not better

### ISSUE THREAD

**Issue by Violet-Nonbloosom** [RelativoBR/Supreme#17]
## Description (Required)
When you put high tier Mutation TechMobs in Tech Generator, you will find that their effects are the same as those in tier 1.

Under other circumstances, such as Tech Mutations, they are at proper tier.

## Steps to reproduce the Issue (Required)
![GIF](https://user-images.githubusercontent.com/86547296/192672670-2cec1ba0-1801-4fcf-9a34-b8c501599812.gif)

## Expected behavior (Required)
Change codes in `MobTech.buildMutation(Supreme, MobTechGeneric)`.

## Server Log / Error Report
This is needless.

## Environment (Required)

![图片](https://user-images.githubusercontent.com/86547296/192673093-bf83fe95-40af-44eb-9de3-f8e26960788d.png)

**Comment by RelativoBR** [comment]
Thanks for reporting the incident, I will make the correction.

**Comment by RelativoBR** [comment]
We identified the flaw, the item was fixed and we also adjusted the descriptions with percentage rate (%). Fixed On branch october-2022
