### ISSUE TITLE
Cetrus Lux Not Craftable

### ISSUE THREAD

**Issue by Azakaturan** [RelativoBR/Supreme#18]
## Description (Required)
I tried to craft the Cetrux Lux in both the Magic Fabricator and the Electric Magical Machine after a player reported that he couldn't craft it, and neither one recognizes the recipe as valid.

## Steps to reproduce the Issue (Required)
https://gyazo.com/4831251455eb446536fdbee385553d92

## Expected behavior (Required)
Craft the item.

## Server Log / Error Report
No errors

## Environment (Required)

 - Minecraft Version: 1.19.2
 - CS-CoreLib Version: N/A
 - Slimefun Version: 1034
 - Plugin Version: 13

**Comment by Violet-Nonbloosom** [comment]
I tried to reproduce this bug, but failed.

![GIF](https://user-images.githubusercontent.com/86547296/195529200-e4525cd0-8f92-4124-bf3c-c64190ec48f9.gif)

![GIF2](https://user-images.githubusercontent.com/86547296/195529531-04351b81-1611-48e4-ae3a-cc823430c653.gif)

This is the setup of my server:

![图片](https://user-images.githubusercontent.com/86547296/195529585-01f5b92f-66b4-4b01-9ec5-332b550b2409.png)

I have no idea why this bug take place.

**Comment by RelativoBR** [comment]
Thanks for reporting the incident, I'll check the situation.

**Comment by RelativoBR** [comment]
No bugs were found, you just need to wait for the processing time, after removing the items you have to wait for the machine to load and it will generate the cetrus.
