### ISSUE TITLE
Mob collector info has a typo

### ISSUE THREAD

**Issue by xX-GATT-Xx** [RelativoBR/Supreme#19]
Description:
Mob Collector is showing incorrect data. it says you need an iron sword to get zombie flesh in the guide, but it needs shears instead.
Steps to reproduce the Issue (Required)

1)get mob collector and sf guide.
2) see what item corresponds to zombie flesh.
3) try it and see it doesn't work. proceed to pull hair for 10min
4)try shears and it works.
Expected behavior (Required)

i expected the guide to show the correct item
Server Log / Error Report
N/A as its a typo
Environment (Required)
![image](https://user-images.githubusercontent.com/32027056/195959317-ac1a109d-5f63-4334-8680-a8148b94e4f9.png)
![image](https://user-images.githubusercontent.com/32027056/195959319-29f0e9ce-5485-4888-a746-225df530e33f.png)
![image](https://user-images.githubusercontent.com/32027056/195959325-23475a31-091a-4579-9fbf-6d8b38ca3f83.png)

**Comment by RelativoBR** [comment]
Thanks for reporting the incident, I will make the correction.

**Comment by xX-GATT-Xx** [comment]
no problem. always love to help

**Comment by RelativoBR** [comment]
Fixed On branch october-2022
