### ISSUE TITLE
SlimefunOreChunks items not working in Quarry

### ISSUE THREAD

**Issue by N1kyZ** [RelativoBR/Supreme#6]
SlimefunOreChunks items do not work in Quarrys

![image](https://user-images.githubusercontent.com/58773688/172169590-7838555b-8596-431c-8692-21b85228ab73.png)

![image](https://user-images.githubusercontent.com/58773688/172169823-16f35873-5b56-47dc-b793-26e9f9f74273.png)

  SlimefunOreChunks vDEV - 15 (git 2520cb23)
  Supreme vDEV - 5 (git 65410777)

 - Minecraft Version: 1.17.1
 - Slimefun Version: Slimefun version DEV - 1014 (git f431aa6d)

**Comment by RelativoBR** [comment]
![image](https://user-images.githubusercontent.com/36118424/173712577-5c5dc52b-2551-4dd3-99ec-237081031261.png)

Hello, I appreciate your feedback, but I couldn't reproduce this error, because I didn't find this ID inside the Slimefun items.

See that it has the option "is-slimefun: true"
