### ISSUE TITLE
Crafting components can be placed and drop vanilla blocks

### ISSUE THREAD

**Issue by JasperChaseTOQ** [RelativoBR/Supreme#9]
## Description (Required)

you can place inductive machines which are a crafting component and when you try to break them it drops the vanilla block 
## Steps to reproduce the Issue (Required)

place any crafting recipe block (EX: inductive machine)
break said block
## Expected behavior (Required)

you should not be able to place crafting items or at the very least it should drop the item when broken 
## Environment (Required)

 - Minecraft Version:
 - Slimefun Version: 1022
 - Plugin Version: 1.3.1

**Comment by RelativoBR** [comment]
All the resources of the supreme should not be possible to put on the ground, both the blocks and the heads, I will investigate the case and include another restriction in addition to the one that already exists today `implements NotPlaceable`

**Comment by RelativoBR** [comment]
Fix on build Supreme v1.3.2
